#!/bin/sh

echo 'Running git pre-commit tests'

# Run TSLint against any staged (added, copied or modified) files with names
# ending in ".ts". If there are any TSLint errors the commit will be aborted.
TS_FILES="$(git diff --cached --name-only --diff-filter=ACM | grep '.ts$')"
if [ ! -z "$TS_FILES" ]; then
  echo $TS_FILES | xargs npm run lint || { exit 1; }
else
  echo 'No staged TypeScript files... skipping TSLint'
fi
