#!/bin/sh

echo 'Running git pre-push tests'

# Run TSLint against any staged (added, copied or modified) files with names
# ending in ".ts". If there are any TSLint errors the push will be aborted.
TS_FILES="$(git diff --cached --name-only --diff-filter=ACM origin/master | grep '.ts$')"
if [ ! -z "$TS_FILES" ]; then
  echo $TS_FILES | xargs npm run lint || { exit 1; }
else
  echo 'No staged JavaScript files... skipping TSLint'
fi

# Run unit tests. If there are any failures the push will be aborted.
CI=true npm t
exit $?
